# numpy 中的合并操作教学

In [2]:
import numpy as np
A = np.array([1,1,1])
B = np.array([2,2,2])

## vertical stack本身属于一种上下合并，即对括号中的两个整体进行对应操作

In [3]:
C = np.vstack((A,B)) # vertical stack
print(C)

[[1 1 1]
 [2 2 2]]


## hstack左右合并

In [4]:
D =  np.hstack((A,B))   # horizontal stack
print(D)

[1 1 1 2 2 2]


## newaxis可以为 numpy.ndarray（多维数组）增加一个轴
np.newaxis 在使用和功能上等价于 None，其实就是 None 的一个别名

In [5]:
print(A)

[1 1 1]


In [6]:
print(A[np.newaxis,:])

[[1 1 1]]


In [7]:
print(A[:,np.newaxis])

[[1]
 [1]
 [1]]


In [8]:
print(A[None,:])

[[1 1 1]]


In [9]:
print(A[:,None])

[[1]
 [1]
 [1]]


## np.concatenate()当你的合并操作需要针对多个矩阵或序列时，借助concatenate函数可能会让你使用起来比前述的函数更加方便：

In [11]:
F = np.concatenate((A,B,B,A),axis=0)
print(F)

[1 1 1 2 2 2 2 2 2 1 1 1]


In [14]:
# 直接F = np.concatenate((A,B),axis=1) 会报错
F = np.concatenate((A[:,np.newaxis],B[:,np.newaxis]),axis=1)
print(F)

[[1 2]
 [1 2]
 [1 2]]


# numpy 中的分割操作教学

In [3]:
A = np.arange(12).reshape((3, 4))
print(A)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


## 纵向分割:split

In [5]:
C,D = np.split(A, 2, axis=1)

In [7]:
print(C)

[[0 1]
 [4 5]
 [8 9]]


In [8]:
print(D)

[[ 2  3]
 [ 6  7]
 [10 11]]


In [9]:
print(np.split(A, 3, axis=0))

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]


## 不等量的分割:array_split

In [12]:
print(np.array_split(A, 3, axis=1))

[array([[0, 1],
       [4, 5],
       [8, 9]]), array([[ 2],
       [ 6],
       [10]]), array([[ 3],
       [ 7],
       [11]])]
